export default () => {
  const froala_config = {
    height: 600,
    // inlineMode: false,
    pastePlain: false,
    pasteDeniedTags: [],
    pasteDeniedAttributes: [],
    wordPasteModal: false,
    paragraphy: false,
    quickInsertEnabled: false,
    toolbarButtons: [
      "undo",
      "redo",
      "fullscreen",
      "|",
      "fontFamily",
      "paragraphFormat",
      "fontSize",
      "textColor",
      "backgroundColor",
      "color",
      "bold",
      "italic",
      "underline",
      "inlineClass",
      "subscript",
      "superscript",
      "|",
      "align",
      "outdent",
      "indent",
      "|",
      "formatOL",
      "formatUL",
      "quote",
      "-",
      "insertLink",
      "insertImage",
      "insertVideo",
      "insertFile",
      "insertTable",
      "|",
      "insertHR",
      "selectAll",
      "clearFormatting",
      "|",
      "print",
      "getPDF",
      "html",
      "wirisEditor",
      "wirisChemistry",
      "fontAwesome",
    ],
    htmlAllowedTags: [".*", "i", "em", "strong", "a", "br", "ul", "li"],
    htmlAllowedAttrs: [".*", "class", "href", "target", "style"],
    placeholderText: "",
    attribution: false,
    key: "",
    disableRightClick: true,
    imageUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/image`,
    imageAllowedTypes: ["jpeg", "jpg", "png"],
    fileUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/document`,
    videoUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/video`,
    // fileUpload: false,
    // imageUpload: false,
    imagePaste: false,
    imagePasteProcess: false,
    imageResize: true,
    crossDomain: true,
    pasteAllowedStyleProps: ["*"],
    pasteAllowLocalImages: true,
    htmlAllowComments: true,
    htmlExecuteScripts: false,
    fontSizeSelection: true,
    //  : "18",
    fontFamily: {
      "Sarabun,sans-serif": "Sarabun",
      "Arial,Helvetica,sans-serif": "Arial",
      //   defaultSelection: "THSarabunNew",
      //   list: {
      //     "THSarabunNew,sans-serif": "TH Sarabun New",
      //   },
    },
    fontDefaultSelection: "Sarabun",
    fontSize: [
      "8",
      "10",
      "12",
      "14",
      "16",
      "18",
      "20",
      "22",
      "24",
      "30",
      "36",
      "48",
      "60",
      "72",
    ],
    tabSpaces: 4,
  };

  return {
    froala_config,
  };
};
