export default () => {
  const froala_config = {
    height: 300,
    // inlineMode: false,
    pastePlain: false,
    pasteDeniedTags: [],
    pasteDeniedAttributes: [],
    wordPasteModal: false,
    paragraphy: false,
    quickInsertEnabled: false,
    toolbarButtons: [
      "undo",
      "redo",
      "fullscreen",
      "|",
      "fontSize",
      "textColor",
      "backgroundColor",
      "color",
      "bold",
      "italic",
      "underline",
      "inlineClass",
      "subscript",
      "superscript",
      "|",
      "paragraphFormat",
      "align",
      "outdent",
      "indent",
      "|",
      "formatOL",
      "formatUL",
      "quote",
      "-",
      "insertLink",
      "insertImage",
      "insertVideo",
      "insertFile",
      "insertTable",
      "|",
      "insertHR",
      "selectAll",
      "clearFormatting",
      "|",
      "print",
      "getPDF",
      "html",
      "wirisEditor",
      "wirisChemistry",
      "fontAwesome",
    ],
    htmlAllowedTags: [".*", "i", "em", "strong", "a", "br", "ul", "li"],
    htmlAllowedAttrs: [".*", "class", "href", "target", "style"],
    placeholderText: "",
    attribution: false,
    key: "enter-your-license-key-here",
    disableRightClick: true,
    imageUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/image`,
    imageAllowedTypes: ["jpeg", "jpg", "png"],
    fileUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/document`,
    videoUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/video`,
    // fileUpload: false,
    // imageUpload: false,
    imagePaste: false,
    imagePasteProcess: false,
    imageResize: true,
    crossDomain: true,
    pasteAllowedStyleProps: ["*"],
    pasteAllowLocalImages: true,
    htmlAllowComments: true,
    htmlExecuteScripts: true,
    fontSizeSelection: true,
    fontSizeDefaultSelection: "18",
  };

  return {
    froala_config,
  };
};
